# Dokumentasi Untuk Visualisasi EDOM

## Deskripsi

Dalam notebook ini, kita akan melakukan visualisasi data EDOM (Evaluasi Dosen Mata Kuliah) menggunakan pandas dan matplotlib. Data EDOM yang digunakan disimpan dalam file Excel dengan format XLSX.

## Langkah-langkah - Data Preparation
1. Pastikan Struktur data sama dengan apa yang sudah ada! Jika tidak, laporkan Ke Atasan Kamu.
2. Simpan File Excel yang diberikan oleh Stakeholder(Atasan Kamu)
3. Masukkan Kedalam Folder yang telah dibuat
4. Pastikan membuat penamaan yang konsisten Contoh : EDOM_GJL_22_23.xlsx

## Langkah-langkah - Data Preparation 2
1. 
2. 
3. 



## Langkah-langkah - Code 

1. Import library yang diperlukan:
    ```python
    import pandas as pd
    import matplotlib.pyplot as plt
    ```

2. Baca file Excel dan simpan data ke dalam DataFrame:
    ```python
    file_path = "aset/asetEdomGanjil2223.xlsx"
    file_sheet = "Informatika"
    df = pd.read_excel(file_path, sheet_name=file_sheet)
    ```

3. Tampilkan data sebagai tabel:
    ```python
    print(df.to_string())
    ```

4. Visualisasikan data menggunakan grafik batang:
    ```python
    df['Nama Dosen'].value_counts().plot(kind='bar')
    plt.xlabel('Nama Dosen')
    plt.ylabel('Jumlah Evaluasi')
    plt.title('Jumlah Evaluasi per Nama Dosen')
    plt.show()
    ```

# HAPPY CODING!

In [2]:
import pandas as pd

class ExcelToDataFrame:
    def __init__(self, file_path, sheet_name):
        self.file_path = file_path
        self.sheet_name = sheet_name

    def read_data(self):
        """Reads data from the specified sheet and returns a DataFrame."""
        return pd.read_excel(self.file_path, sheet_name=self.sheet_name)
    
    def read_column(self, column_name):
        """Reads data from the specified column and returns a Series."""
        return pd.read_excel(self.file_path, sheet_name=self.sheet_name, usecols=column_name)
    
    def insert_data(self, data, destination_sheet):
        """Inserts data to the specified sheet."""
        with pd.ExcelWriter(self.file_path, engine='openpyxl') as writer:
            # Read the existing Excel file
            existing_data = pd.read_excel(self.file_path, sheet_name=destination_sheet)
            
            # Append the new data to the existing data
            updated_data = existing_data.append(data, ignore_index=True)
            
            # Write the updated data back to the Excel file
            updated_data.to_excel(writer, sheet_name=destination_sheet, index=False)
    
    def get_data_types_and_column(df):
    for sheet_name in xl.sheet_names:
        # Read the entire sheet
        df = xl.parse(sheet_name)
        print(f"Sheet: {sheet_name}\n\nColumns and Data Types:\n", df.dtypes, df.columns)

# Example usage:
            
dir_to_df_file_name = "aset/asetEdomGanjil2223.xlsx"
sheet_name_from_df = "Seluruh Dosen"
df = ExcelToDataFrame(dir_to_df_file_name, sheet_name=sheet_name_from_df)

# Print the updated data
print(df.read_data())

      No Kode \n Dosen                      Nama Dosen  \
0      1           KMD    KHARISMA MONIKA DIAN PERTIWI
1      2           ARD          ARDIAN YUSUF WICAKSONO
2      3           ALR                ALQIS RAUSANFITA
3      4           AWS  AHMAD WALI SATRIA BAHARI JOHAN
4      5           VRO             VESSA RIZKY OKTAVIA
..   ...           ...                             ...
176  177           NaN                             NaN
177  178           NaN                             NaN
178  179           NaN                             NaN
179  180           NaN                             NaN
180  181           NaN                             NaN

                      Status  Jumlah Kelas  Jumlah Mahasiswa  Persentase EDOM  \
0    DOSEN TETAP (FULL TIME)           3.0              93.0            81.29
1    DOSEN TETAP (FULL TIME)           3.0              77.0            85.07
2    DOSEN TETAP (FULL TIME)           4.0             112.0            85.52
3    DOSEN TETAP (FULL TIME)           4.0             128.0            87.96
4    DOSEN TETAP (FULL TIME)           4.0             124.0            89.19
..                       ...           ...               ...              ...
176                      NaN           NaN               NaN              NaN
177                      NaN           NaN               NaN              NaN
178                      NaN           NaN               NaN              NaN
179                      NaN           NaN               NaN              NaN
180                      NaN           NaN               NaN              NaN

              Prodi
0       Informatika
1       Informatika
2       Informatika
3       Informatika
4       Informatika
..              ...
176  Teknik Elektro
177  Teknik Elektro
178  Teknik Elektro
179  Teknik Elektro
180  Teknik Elektro

[181 rows x 8 columns]

Properti Data

In [34]:
import pandas as pd

# Step 1: Read the Excel file
file_path = 'aset/asetEdomGanjil2223.xlsx'
df = pd.read_excel(file_path, sheet_name='Seluruh Dosen')

# Step 2: Create a new sheet and copy the data
    new_sheet_name = '2'
    with pd.ExcelWriter(file_path, engine='openpyxl', mode='a') as writer:
        df.to_excel(writer, sheet_name=new_sheet_name, index=False)

# Step 3: Print the data from the new sheet
new_sheet_df = pd.read_excel(file_path, sheet_name=new_sheet_name)
print(new_sheet_df)

      No Kode \n Dosen                      Nama Dosen  \
0      1           KMD    KHARISMA MONIKA DIAN PERTIWI
1      2           ARD          ARDIAN YUSUF WICAKSONO
2      3           ALR                ALQIS RAUSANFITA
3      4           AWS  AHMAD WALI SATRIA BAHARI JOHAN
4      5           VRO             VESSA RIZKY OKTAVIA
..   ...           ...                             ...
176  177           NaN                             NaN
177  178           NaN                             NaN
178  179           NaN                             NaN
179  180           NaN                             NaN
180  181           NaN                             NaN

                      Status  Jumlah Kelas  Jumlah Mahasiswa  Persentase EDOM  \
0    DOSEN TETAP (FULL TIME)           3.0              93.0            81.29
1    DOSEN TETAP (FULL TIME)           3.0              77.0            85.07
2    DOSEN TETAP (FULL TIME)           4.0             112.0            85.52
3    DOSEN TETAP (FULL TIME)           4.0             128.0            87.96
4    DOSEN TETAP (FULL TIME)           4.0             124.0            89.19
..                       ...           ...               ...              ...
176                      NaN           NaN               NaN              NaN
177                      NaN           NaN               NaN              NaN
178                      NaN           NaN               NaN              NaN
179                      NaN           NaN               NaN              NaN
180                      NaN           NaN               NaN              NaN

              Prodi
0       Informatika
1       Informatika
2       Informatika
3       Informatika
4       Informatika
..              ...
176  Teknik Elektro
177  Teknik Elektro
178  Teknik Elektro
179  Teknik Elektro
180  Teknik Elektro

[181 rows x 8 columns]

:

In [10]:
# Cara Menghitung Nama Dosen
hitung_nama_dosen = len(df['Nama Dosen'].unique())
hitungNamaDosen = df['Nama Dosen'].count()

print("Nama dosen:", hitung_nama_dosen, "orang")

# Iterate through the unique lecturer names and print each one
for name in df['Nama Dosen'].unique():
    print(name)

TypeError: string indices must be integers, not 'str'