In [32]:
import pandas as pd

filename = 'aset/asetEdomGanjil2223.xlsx'
xl = pd.ExcelFile(filename)

# Get sheet names
sheet_names = xl.sheet_names

# Create a writer for the merged data
writer = pd.ExcelWriter('aset/mergedData.xlsx', engine='xlsxwriter')

# Create an empty DataFrame to store combined data
combined_data = pd.DataFrame()

# Iterate over sheet names
for sheet_name in sheet_names:
    # Read each sheet
    df = xl.parse(sheet_name, parse_dates=True)
    
    # Concatenate the data to the combined_data DataFrame
    combined_data = pd.concat([combined_data, df], ignore_index=True)

# Write the combined data to a new Excel file
combined_data.to_excel(writer, index=False, sheet_name='CombinedData')

# Save the Excel file
writer.close()

Seluruh Dosen:
       1  KMD    KHARISMA MONIKA DIAN PERTIWI  DOSEN TETAP (FULL TIME)   3  \
0      2  ARD          ARDIAN YUSUF WICAKSONO  DOSEN TETAP (FULL TIME)   3
1      3  ALR                ALQIS RAUSANFITA  DOSEN TETAP (FULL TIME)   4
2      4  AWS  AHMAD WALI SATRIA BAHARI JOHAN  DOSEN TETAP (FULL TIME)   4
3      5  VRO             VESSA RIZKY OKTAVIA  DOSEN TETAP (FULL TIME)   4
4      6  MDF        MUHAMMAD DZULFIKAR FAUZI  DOSEN TETAP (FULL TIME)   2
..   ...  ...                             ...                      ...  ..
175  177  ISA                      ISA HAFIDZ              DOSEN TETAP   3
176  178  AMI                 KHODIJAH AMIROH              DOSEN TETAP   6
177  179  DRZ          DARIL RIDHO ZUCHRILLAH         DOSEN LUAR BIASA   5
178  180  GFD             GINA FAAIZATUD DINI         DOSEN LUAR BIASA   7
179  181  HAR                        HARMANTO         DOSEN LUAR BIASA  10

      93  81.29     Informatika
0     77  85.07     Informatika
1    112  85.52     Informatika
2    128  87.96     Informatika
3    124  89.19     Informatika
4     72  88.25     Informatika
..   ...    ...             ...
175   81  78.34  Teknik Elektro
176  377  78.23  Teknik Elektro
177  150  86.07  Teknik Elektro
178  215  88.28  Teknik Elektro
179  476  84.16  Teknik Elektro

[180 rows x 8 columns]

Informatika:
     1  KMD    KHARISMA MONIKA DIAN PERTIWI  DOSEN TETAP (FULL TIME)   3   93  \
0    2  ARD          ARDIAN YUSUF WICAKSONO  DOSEN TETAP (FULL TIME)   3   77
1    3  ALR                ALQIS RAUSANFITA  DOSEN TETAP (FULL TIME)   4  112
2    4  AWS  AHMAD WALI SATRIA BAHARI JOHAN  DOSEN TETAP (FULL TIME)   4  128
3    5  VRO             VESSA RIZKY OKTAVIA  DOSEN TETAP (FULL TIME)   4  124
4    6  MDF        MUHAMMAD DZULFIKAR FAUZI  DOSEN TETAP (FULL TIME)   2   72
5    7  HMM     MOH. HAMIM ZAJULI AL FAROBY  DOSEN TETAP (FULL TIME)   4   93
6    8  RFM           RIZKY FENALDO MAULANA  DOSEN TETAP (FULL TIME)   3   97
7    9  AMI                 KHODIJAH AMIROH              DOSEN TETAP   6  377
8   10  UIS               ULFA INAS SAYEKTI         DOSEN LUAR BIASA  10  332
9   11  SSL                  SAMSUL HIDAYAT         DOSEN LUAR BIASA   4  128
10  12  SDN                   SADIN SUBEKTI         DOSEN LUAR BIASA   4  101
11  13  RNH       RIZKY NOVERA HARNANINGRUM         DOSEN LUAR BIASA   5  161
12  14  JTS            JUSAK TJIPTO SANTOSO         DOSEN LUAR BIASA   4   30
13  15  IKS              JM. I KETUT SEDANA         DOSEN LUAR BIASA   2    2
14  16  HAR                        HARMANTO         DOSEN LUAR BIASA  10  476
15  17  GUS                         MINGGUS         DOSEN LUAR BIASA   4   17

    81.29
0   85.07
1   85.52
2   87.96
3   89.19
4   88.25
5   88.21
6   88.34
7   78.23
8   68.60
9   87.78
10  89.41
11  79.35
12  86.38
13  80.77
14  84.16
15  84.98

Bisnis Digital:
     1  RAS    RIZA AKHSANI SETYO PRAYOGA  DOSEN TETAP (FULL TIME)   5  157  \
0    2  RFD               RIFDATUN NI'MAH  DOSEN TETAP (FULL TIME)   5  122
1    3  WYR         WACHDA YUNIAR ROCHMAH  DOSEN TETAP (FULL TIME)   5  127
2    4  DAU                  DARLIN AULIA  DOSEN TETAP (FULL TIME)   5  142
3    5  AAF  ARRIZKY AYU FARADILA PURNAMA  DOSEN TETAP (FULL TIME)   7  250
4    6  SWP         SEKAR WIDYASARI PUTRI  DOSEN TETAP (FULL TIME)   5  164
5    7  DMI         DOMINGGO BAYU BASKARA              DOSEN TETAP   4  131
6    8  ANO        CAESAREANO LAFADO YESA              DOSEN TETAP   6  172
7    9  AGW                AGOES WINDARTO              DOSEN TETAP   2   44
8   10  AMI               KHODIJAH AMIROH              DOSEN TETAP   6  377
9   11  SMH           SITI MAIZUL HABIBAH         DOSEN LUAR BIASA  10  348
10  12  UIS             ULFA INAS SAYEKTI         DOSEN LUAR BIASA  10  332
11  13  HRM              HARUM MUNAZHAROH         DOSEN LUAR BIASA   2   59

     90.1
0   87.43
1   90.37
2   89.72
3   84.56
4   85.95
5   88.22
6   92.14
7   86.88
8   78.23
9   84.68
10  68.60
11  80.52

Sains Data:
     1  RGT         REGITA PUTRI PERMATA  DOSEN TETAP (FULL TIME)  4   86  \
0    2  HMM  MOH. HAMIM ZAJULI AL FAROBY  DOSEN TETAP (FULL TIME)  4   93
1    3  HNF        HELISYAH NUR FADHILAH  DOSEN TETAP (FULL TIME)  3   79
2    4  ANA            AMALIA NUR ALIFAH  DOSEN TETAP (FULL TIME)  5  123
3    5  ALR             ALQIS RAUSANFITA  DOSEN TETAP (FULL TIME)  4  112
4    6  RFD              RIFDATUN NI'MAH  DOSEN TETAP (FULL TIME)  5  122
5    7  GUS                      MINGGUS         DOSEN LUAR BIASA  4   17
6    8  JTS         JUSAK TJIPTO SANTOSO         DOSEN LUAR BIASA  4   30
7    9  IKS           JM. I KETUT SEDANA         DOSEN LUAR BIASA  2    2
8   10  ALD             ALDA DEA DELFINA         DOSEN LUAR BIASA  1   22
9   11  AAS            AGUNG ARI SUBAGIO         DOSEN LUAR BIASA  4  121
10  12  HPP          HENDRIK PANDU PAKSI         DOSEN LUAR BIASA  1   43

    85.54
0   88.21
1   83.43
2   89.10
3   85.52
4   87.43
5   84.98
6   86.38
7   80.77
8   88.03
9   81.88
10  74.30

Teknik Logistik:
   1  DNR  DESITA NUR RACHMANIAR  DOSEN TETAP (FULL TIME)   5  118  88.89
0  2  NIS            NISA ISROFI  DOSEN TETAP (FULL TIME)   6  134  83.82
1  3  GRA          GRANITA HAJAR  DOSEN TETAP (FULL TIME)   4   81  87.37
2  4  ASA     ABDUH SAYID ALBANA              DOSEN TETAP   4   78  85.73
3  5  SMH    SITI MAIZUL HABIBAH         DOSEN LUAR BIASA  10  348  84.68
4  6  SAL          SAIDAH ALTWAY         DOSEN LUAR BIASA   1   19  77.56
5  7  AFM  ANISA FITRI MUYASAROH         DOSEN LUAR BIASA   1   21  83.33
6  8  HRM       HARUM MUNAZHAROH         DOSEN LUAR BIASA   2   59  80.52

Teknik Komputer:
     1  MYH MOHAMMAD YANUAR HARIYAWAN  DOSEN TETAP (FULL TIME)   5  147  87.66
0    2  AFD       AHMAD FAISAL DAHLAN  DOSEN TETAP (FULL TIME)   2   76  84.18
1    3  NIR              NANDA IRYANI  DOSEN TETAP (FULL TIME)   6  233  90.24
2    4  GRA             GRANITA HAJAR  DOSEN TETAP (FULL TIME)   4   81  87.37
3    5  ONI            CHAIRONI LATIF  DOSEN TETAP (FULL TIME)   4  124  88.69
4    6  DNR     DESITA NUR RACHMANIAR  DOSEN TETAP (FULL TIME)   5  118  88.89
5    7  ARA        AULIA RAHMA ANNISA  DOSEN TETAP (FULL TIME)   5  147  89.48
6    8  KHL        LORA KHAULA AMIFIA              DOSEN TETAP   5  174  85.37
7    9  UBM           UBAIDILLAH UMAR              DOSEN TETAP   3  105  87.43
8   10  BLM           BILLY MONTOLALU              DOSEN TETAP   4  133  86.56
9   11  ALF      ARDIANSYAH AL FAROUQ              DOSEN TETAP   5  147  91.07
10  12  EDS          DWI EDI SETYAWAN              DOSEN TETAP   3   90  93.69
11  13  HAR                  HARMANTO         DOSEN LUAR BIASA  10  476  84.16

Teknologi Informasi:
     1  MUS              MUSTAFA KAMAL  DOSEN TETAP (FULL TIME)  5  143  88.84
0    2  DIB       MUHAMMAD ADIB KAMALI  DOSEN TETAP (FULL TIME)  5  164  88.57
1    3  NAS          MUHAMAD NASRULLAH  DOSEN TETAP (FULL TIME)  5  174  85.09
2    4  FZN             FAUZAN NUSYURA  DOSEN TETAP (FULL TIME)  4  117  86.24
3    5  BAS    BERNADUS ANGGO SENO AJI  DOSEN TETAP (FULL TIME)  4  147  87.68
4    6  YOS           YOHANES SETIAWAN  DOSEN TETAP (FULL TIME)  5  121  89.61
5    7  AMI            KHODIJAH AMIROH              DOSEN TETAP  6  377  78.23
6    8  HEL           HELMY WIDYANTARA              DOSEN TETAP  3  109  89.17
7    9  RSY    MOCH. ISKANDAR RIANSYAH              DOSEN TETAP  4  107  85.06
8   10  SSJ      SUSIJANTO TRI RASMANA              DOSEN TETAP  4  119  87.46
9   11  OKT        OKTAVIA AYU PERMATA              DOSEN TETAP  4  114  86.11
10  12  GFD        GINA FAAIZATUD DINI         DOSEN LUAR BIASA  7  215  88.28
11  13  ADR  ANDREAS NUGROHO SIHANANTO         DOSEN LUAR BIASA  2   45  90.13
12  14  RZK               RIZAL KUDDAH         DOSEN LUAR BIASA  4  105  82.45
13  15  AAS          AGUNG ARI SUBAGIO         DOSEN LUAR BIASA  4  121  81.88
14  16  GUS                    MINGGUS         DOSEN LUAR BIASA  4   17  84.98
15  17  GSP            GAGUK SUPRIANTO         DOSEN LUAR BIASA  4  139  86.23
16  18  GAB  I GEDE AREI BANYUPREMESTA         DOSEN LUAR BIASA  1   46  87.12
17  19  JTS       JUSAK TJIPTO SANTOSO         DOSEN LUAR BIASA  4   30  86.38
18  20  WIN          WINDI PUSPITASARI         DOSEN LUAR BIASA  4  128  84.46

RPL:
     1  ARS              ARIS KUSUMAWATI  DOSEN TETAP (FULL TIME)   5  161  \
0    2  AAH  ALIFIANSYAH ARRIZQY HIDAYAT  DOSEN TETAP (FULL TIME)   5  148
1    3  ZAK               ACHMAD MUZAKKI  DOSEN TETAP (FULL TIME)   4  105
2    4  MSK              MOHAMMAD SHOLIK              DOSEN TETAP   4  100
3    5  DEW               DEWI RAHMAWATI              DOSEN TETAP   3   48
4    6  FWP           FIDI WINCOKO PUTRO              DOSEN TETAP   5  115
5    7  TTK              TITUS KRISTANTO              DOSEN TETAP   5  128
6    8  PNG              PANGESTU WIDODO              DOSEN TETAP   5  146
7    9  SMH          SITI MAIZUL HABIBAH         DOSEN LUAR BIASA  10  348
8   10  RZK                 RIZAL KUDDAH         DOSEN LUAR BIASA   4  105
9   11  GUS                      MINGGUS         DOSEN LUAR BIASA   4   17
10  12  JTS         JUSAK TJIPTO SANTOSO         DOSEN LUAR BIASA   4   30
11  13  IKS           JM. I KETUT SEDANA         DOSEN LUAR BIASA   2    2
12  14  HAR                     HARMANTO         DOSEN LUAR BIASA  10  476
13  15  GFD          GINA FAAIZATUD DINI         DOSEN LUAR BIASA   7  215
14  16  ESO            EKA SARI OKTARINA         DOSEN LUAR BIASA   6  203
15  17  AAS            AGUNG ARI SUBAGIO         DOSEN LUAR BIASA   4  121

    86.14
0   88.59
1   90.61
2   87.19
3   87.20
4   91.89
5   83.89
6   91.60
7   84.68
8   82.45
9   84.98
10  86.38
11  80.77
12  84.16
13  88.28
14  88.10
15  81.88

Teknik Telekomunikasi:
     1  NRR           NILLA RACHMANINGRUM      DOSEN TETAP (FULL TIME)   7  \
0    2  ONI                CHAIRONI LATIF      DOSEN TETAP (FULL TIME)   4
1    3  RMU          RISDILAH MIMMA UNTSA      DOSEN TETAP (FULL TIME)   4
2    4  FSA           FANNUSH SHOFI AKBAR      DOSEN TETAP (FULL TIME)   4
3    5  AAF  ARRIZKY AYU FARADILA PURNAMA      DOSEN TETAP (FULL TIME)   7
4    6  MYH     MOHAMMAD YANUAR HARIYAWAN      DOSEN TETAP (FULL TIME)   5
5    7  HAM       HAMZAH ULINUHA MUSTAKIM                  DOSEN TETAP   9
6    8  UCN                        MUHSIN                  DOSEN TETAP   4
7    9  WLD      WALID MAULANA HADIANSYAH                  DOSEN TETAP   3
8   10  TRI       TRI AGUS DJOKO KUNTJORO  DOSEN PROFESIONAL FULL TIME   8
9   11  SMH           SITI MAIZUL HABIBAH             DOSEN LUAR BIASA  10
10  12  DRZ        DARIL RIDHO ZUCHRILLAH             DOSEN LUAR BIASA   5

    179  83.44
0   124  88.69
1    82  84.13
2    88  88.56
3   250  84.56
4   147  87.66
5   290  86.61
6   133  86.16
7    89  84.44
8   220  91.30
9   348  84.68
10  150  86.07

Sistem Informasi:
     1  AHN          ANITA HAKIM NASUTION  DOSEN TETAP (FULL TIME)   4   87  \
0    2  ARR                  ARIP RAMADAN  DOSEN TETAP (FULL TIME)   5  165
1    3  ARS               ARIS KUSUMAWATI  DOSEN TETAP (FULL TIME)   5  161
2    4  BRL       BERLIAN RAHMY LIDIAWATY  DOSEN TETAP (FULL TIME)   5  182
3    5  AND             ANISA DZULKARNAIN  DOSEN TETAP (FULL TIME)   5  168
4    6  ANA             AMALIA NUR ALIFAH  DOSEN TETAP (FULL TIME)   5  123
5    7  AAH   ALIFIANSYAH ARRIZQY HIDAYAT  DOSEN TETAP (FULL TIME)   5  148
6    8  AFF           AFFIFIANA PRISYANTI  DOSEN TETAP (FULL TIME)   4  152
7    9  ARP       ADZANIL RACHMADHI PUTRA  DOSEN TETAP (FULL TIME)   4  150
8   10  TAR          TITA AYU ROSPRICILIA  DOSEN TETAP (FULL TIME)   5  176
9   11  SRI                  SRI HIDAYATI  DOSEN TETAP (FULL TIME)   4  152
10  12  ROS               ROSYID ABDILLAH  DOSEN TETAP (FULL TIME)   4  108
11  13  RIN              ROKHMATUL INSANI  DOSEN TETAP (FULL TIME)   3   93
12  14  RAS    RIZA AKHSANI SETYO PRAYOGA  DOSEN TETAP (FULL TIME)   5  157
13  15  LIA                  RAULIA RISKI  DOSEN TETAP (FULL TIME)   4  108
14  16  PUR               PURNAMA ANAKING  DOSEN TETAP (FULL TIME)   4  145
15  17  NAS             MUHAMAD NASRULLAH  DOSEN TETAP (FULL TIME)   5  174
16  18  MNP  MOCHAMAD NIZAR PALEFI MA'ADY  DOSEN TETAP (FULL TIME)   5  131
17  19  HNF         HELISYAH NUR FADHILAH  DOSEN TETAP (FULL TIME)   3   79
18  20  YPS                YUPIT SUDIANTO              DOSEN TETAP   4  148
19  21  HWM              HAWWIN MARDHIANA              DOSEN TETAP   5  183
20  22  ULF                   ULLY ASFARI              DOSEN TETAP   5  176
21  23  NPI         NOERMA PUDJI ISTYANTO              DOSEN TETAP   4  130
22  24  AGS                 AGUS SULISTYA  DOSEN PERBANTUAN TELKOM   2   77
23  25  ESO             EKA SARI OKTARINA         DOSEN LUAR BIASA   6  203
24  26  GTA    GITHA ANDANI SUHARNINGTYAS         DOSEN LUAR BIASA   2   51
25  27  YSN                   MOCH. YASIN         DOSEN LUAR BIASA   1   38
26  28  HAR                      HARMANTO         DOSEN LUAR BIASA  10  476
27  29  SST              PRASASTI KARUNIA         DOSEN LUAR BIASA   2   74
28  30  REN                RENI WULANSARI         DOSEN LUAR BIASA   1   22
29  31  ASD              ADITHYA SUDIARNO         DOSEN LUAR BIASA   1   35
30  32  HAN                      HARIANTO         DOSEN LUAR BIASA   3  106
31  33  LSH             LAILATUS SHOLIHAH         DOSEN LUAR BIASA   4  142

    88.87
0   83.65
1   86.14
2   88.75
3   85.98
4   89.10
5   88.59
6   76.06
7   86.59
8   89.52
9   84.23
10  82.69
11  83.65
12  90.10
13  90.75
14  85.04
15  85.09
16  80.38
17  83.43
18  85.65
19  89.50
20  89.56
21  87.85
22  86.77
23  88.10
24  79.88
25  71.38
26  84.16
27  77.94
28  83.59
29  81.28
30  72.06
31  85.75

Teknik Industri:
     1  DNR        DESITA NUR RACHMANIAR  DOSEN TETAP (FULL TIME)   5  118  \
0    2  PSP         PERDANA SUTEJA PUTRA  DOSEN TETAP (FULL TIME)   5  146
1    3  NIS                  NISA ISROFI  DOSEN TETAP (FULL TIME)   6  134
2    4  AFD          AHMAD FAISAL DAHLAN  DOSEN TETAP (FULL TIME)   2   76
3    5  HKC                 HUKI CHANDRA  DOSEN TETAP (FULL TIME)   8  263
4    6  SIL              SILVI ISTIQOMAH  DOSEN TETAP (FULL TIME)   7  239
5    7  AYU            AYU ENDAH WAHYUNI  DOSEN TETAP (FULL TIME)   6  217
6    8  RDP  RAHADITYA DIMAS PRIHADIANTO              DOSEN TETAP   3  110
7    9  ASA           ABDUH SAYID ALBANA              DOSEN TETAP   4   78
8   10  RAZ         RIZQA AMELIA ZUNAIDI              DOSEN TETAP   7  206
9   11  WAP       WAHYU ANDY PRASTYABUDI              DOSEN TETAP   4  100
10  12  DMI        DOMINGGO BAYU BASKARA              DOSEN TETAP   4  131
11  13  BLW   BAMBANG LELONO WIDJIANTORO              DOSEN TETAP   1   43
12  14  BIA   BENAZIR IMAM ARIF MUTTAQIN              DOSEN TETAP   6   92
13  15  UMS                 UMI MASLAKAH         DOSEN LUAR BIASA   1   31
14  16  UIS            ULFA INAS SAYEKTI         DOSEN LUAR BIASA  10  332
15  17  SMH          SITI MAIZUL HABIBAH         DOSEN LUAR BIASA  10  348
16  18  MSH  MAHENDRA SATRIA HADININGRAT         DOSEN LUAR BIASA   1   32
17  19  IKS           JM. I KETUT SEDANA         DOSEN LUAR BIASA   2    2
18  20  DRZ       DARIL RIDHO ZUCHRILLAH         DOSEN LUAR BIASA   5  150
19  21  ADL               ADELIA SAVITRI         DOSEN LUAR BIASA   2   61

    88.89
0   84.38
1   83.82
2   84.18
3   85.99
4   82.43
5   82.52
6   86.19
7   85.73
8   82.37
9   87.11
10  88.22
11  80.17
12  82.37
13  83.53
14  68.60
15  84.68
16  87.93
17  80.77
18  86.07
19  86.94

Teknik Elektro:
     1  HMM MOH. HAMIM ZAJULI AL FAROBY  DOSEN TETAP (FULL TIME)   4   93  \
0    2  ONI              CHAIRONI LATIF  DOSEN TETAP (FULL TIME)   4  124
1    3  DNR       DESITA NUR RACHMANIAR  DOSEN TETAP (FULL TIME)   5  118
2    4  RIP          RIFKI DWI PUTRANTO  DOSEN TETAP (FULL TIME)   4  100
3    5  DMS              DIMAS ADIPUTRA              DOSEN TETAP   7  177
4    6  SSJ       SUSIJANTO TRI RASMANA              DOSEN TETAP   4  119
5    7  IFA            ANIFATUL FARICHA              DOSEN TETAP   1   31
6    8  ALF        ARDIANSYAH AL FAROUQ              DOSEN TETAP   5  147
7    9  RSY     MOCH. ISKANDAR RIANSYAH              DOSEN TETAP   4  107
8   10  KHL          LORA KHAULA AMIFIA              DOSEN TETAP   5  174
9   11  ISA                  ISA HAFIDZ              DOSEN TETAP   3   81
10  12  AMI             KHODIJAH AMIROH              DOSEN TETAP   6  377
11  13  DRZ      DARIL RIDHO ZUCHRILLAH         DOSEN LUAR BIASA   5  150
12  14  GFD         GINA FAAIZATUD DINI         DOSEN LUAR BIASA   7  215
13  15  HAR                    HARMANTO         DOSEN LUAR BIASA  10  476

    88.21
0   88.69
1   88.89
2   78.74
3   84.90
4   87.46
5   84.62
6   91.07
7   85.06
8   85.37
9   78.34
10  78.23
11  86.07
12  88.28
13  84.16

MergedData:
      1  KMD    KHARISMA MONIKA DIAN PERTIWI  DOSEN TETAP (FULL TIME)   3  \
0     2  ARD          ARDIAN YUSUF WICAKSONO  DOSEN TETAP (FULL TIME)   3
1     3  ALR                ALQIS RAUSANFITA  DOSEN TETAP (FULL TIME)   4
2     4  AWS  AHMAD WALI SATRIA BAHARI JOHAN  DOSEN TETAP (FULL TIME)   4
3     5  VRO             VESSA RIZKY OKTAVIA  DOSEN TETAP (FULL TIME)   4
4     6  MDF        MUHAMMAD DZULFIKAR FAUZI  DOSEN TETAP (FULL TIME)   2
..   ..  ...                             ...                      ...  ..
356  11  ISA                      ISA HAFIDZ              DOSEN TETAP   3
357  12  AMI                 KHODIJAH AMIROH              DOSEN TETAP   6
358  13  DRZ          DARIL RIDHO ZUCHRILLAH         DOSEN LUAR BIASA   5
359  14  GFD             GINA FAAIZATUD DINI         DOSEN LUAR BIASA   7
360  15  HAR                        HARMANTO         DOSEN LUAR BIASA  10

      93  81.29  Informatika  Unnamed: 8
0     77  85.07  Informatika         NaN
1    112  85.52  Informatika         NaN
2    128  87.96  Informatika         NaN
3    124  89.19  Informatika         NaN
4     72  88.25  Informatika         NaN
..   ...    ...          ...         ...
356   81  78.34          NaN         NaN
357  377  78.23          NaN         NaN
358  150  86.07          NaN         NaN
359  215  88.28          NaN         NaN
360  476  84.16          NaN         NaN

[361 rows x 9 columns]

In [4]:
import pandas as pd

filename = "aset/asetEdomGanjil2223.xlsx" # Path to the Excel workbook
writer = pd.ExcelWriter(filename, engine="openpyxl", mode="a") # Open the workbook in append mode with openpyxl engine
sheet_names = pd.ExcelFile(filename).sheet_names # Get all sheet names
sheet_name_to_merge = "MergedData" # Define the target sheet for merging

if sheet_name_to_merge in sheet_names: # Check if the target sheet already exists
    print("⚠️ Data sudah ada di sheet '{}', tolong dicek dulu sebelum dihapus!".format(sheet_name_to_merge))
else:
    combined_data = pd.DataFrame() # Initialize an empty DataFrame for merged data
    for sheet_name in sheet_names: # Loop through each existing sheet
        df = pd.ExcelFile(filename).parse(sheet_name, parse_dates=True) # Read and parse each sheet data
        combined_data = pd.concat([combined_data, df], ignore_index=True) # Append current sheet data to the combined DataFrame
    combined_data.to_excel(writer, index=False, sheet_name=sheet_name_to_merge) # Write the combined data to the target sheet (replace with your desired name)
    writer.close() # Close the workbook and save changes
    print(" Data berhasil di-merge ke sheet '{}'!".format(sheet_name_to_merge)) # Print a success message

⚠️ Data sudah ada di sheet 'MergedData', tolong dicek dulu sebelum dihapus!

In [ ]:
import pandas as pd

filename = "aset/asetEdomGanjil2223.xlsx"

# xl = pd.ExcelFile(filename)

xl = pd.ExcelFile(filename, engine="openpyxl")

def get_data_types(df):
    for sheet_name in xl.sheet_names:
        # Read the entire sheet
        df = xl.parse(sheet_name)
        print(f"Sheet: {sheet_name}\n\nColumns and Data Types:\n", df.dtypes, df.columns)
        
        
get_data_types(xl)

In [1]:
import pandas as pd

def insert_empty_column_with_sheet_name(filename, sheet_name):
    """
    Inserts an empty column with the sheet name in the next available empty column.
    If no empty columns are found, handles the scenario gracefully.

    Args:
        filename (str): The path to the Excel file.
        sheet_name (str): The name of the sheet to process.
    """

    # Open the Excel file in append mode with the appropriate engine
    engine = "openpyxl"  # Use openpyxl for .xlsx files
    writer = pd.ExcelWriter(filename, engine=engine, mode="a")

    # Load the specific sheet into a DataFrame
    df = pd.read_excel(filename, sheet_name=sheet_name, engine=engine)

    # Find the index of the next empty column, handling potential absence of empty columns
    try:
        next_empty_column = next(col for col in df.columns if df[col].isnull().all())
    except StopIteration:
        print(f"No empty columns found in sheet '{sheet_name}'. Skipping...")
        return  # Exit the function if no empty columns are found

    # Insert the new empty column with the sheet name
    df.insert(next_empty_column, sheet_name, pd.NA)

    # Write the modified DataFrame back to the Excel file
    df.to_excel(writer, sheet_name=sheet_name, index=False)

    # Close the writer to save changes
    writer.close()

# Example usage:
filename = 'aset/asetEdomGanjil2223.xlsx'
for sheet_name in pd.ExcelFile(filename).sheet_names:  # Iterate through all sheets
    insert_empty_column_with_sheet_name(filename, sheet_name)

No empty columns found in sheet 'Seluruh Dosen'. Skipping...
No empty columns found in sheet 'Informatika'. Skipping...
No empty columns found in sheet 'Bisnis Digital'. Skipping...
No empty columns found in sheet 'Sains Data'. Skipping...
No empty columns found in sheet 'Teknik Logistik'. Skipping...
No empty columns found in sheet 'Teknik Komputer'. Skipping...
No empty columns found in sheet 'Teknologi Informasi'. Skipping...
No empty columns found in sheet 'RPL'. Skipping...
No empty columns found in sheet 'Teknik Telekomunikasi'. Skipping...
No empty columns found in sheet 'Sistem Informasi'. Skipping...
No empty columns found in sheet 'Teknik Industri'. Skipping...
No empty columns found in sheet 'Teknik Elektro'. Skipping...

In [3]:
import pandas as pd

def insert_empty_column_with_sheet_name(filename, sheet_name):
    """
    Inserts an empty column with the sheet name in the next available empty column,
    prioritizing the column immediately after the last non-empty column.

    Args:
        filename (str): The path to the Excel file.
        sheet_name (str): The name of the sheet to process.
    """

    # Open the Excel file in append mode with the appropriate engine
    engine = "openpyxl"  # Use openpyxl for .xlsx files
    writer = pd.ExcelWriter(filename, engine=engine, mode="a")

    # Load the specific sheet into a DataFrame
    df = pd.read_excel(filename, sheet_name=sheet_name, engine=engine)

    # Find the index of the next empty column, prioritizing the one after the last non-empty column
    try:
        next_empty_column = next(col for col in df.columns if df[col].isnull().all())
    except StopIteration:
        # If no empty columns are found, use the column after the last non-empty column
        next_empty_column = max(df.columns) + 1

    # Insert the new empty column with the sheet name
    df.insert(next_empty_column, sheet_name, pd.NA)

    # Write the modified DataFrame back to the Excel file
    df.to_excel(writer, sheet_name=sheet_name, index=False)

    # Close the writer to save changes
    writer.close()

# Example usage:
filename = 'aset/asetEdomGanjil2223.xlsx'
for sheet_name in pd.ExcelFile(filename).sheet_names:  # Iterate through all sheets
    insert_empty_column_with_sheet_name(filename, sheet_name)

TypeError: can only concatenate str (not "int") to str

In [5]:
import pandas as pd

def insert_empty_column_with_sheet_name(filename, sheet_name):
    """
    Inserts an empty column with the sheet name in the next available empty column,
    prioritizing the column immediately after the last non-empty column.

    Args:
        filename (str): The path to the Excel file.
        sheet_name (str): The name of the sheet to process.
    """

    # Open the Excel file in append mode with the appropriate engine
    engine = "openpyxl"  # Use openpyxl for .xlsx files
    writer = pd.ExcelWriter(filename, engine="openpyxl", mode="a")

    # Load the specific sheet into a DataFrame
    df = pd.read_excel(filename, sheet_name=sheet_name, engine=engine)

    # Find the index of the next empty column, prioritizing the one after the last non-empty column
    try:
        next_empty_column = next(col for col in df.columns if df[col].isnull().all())
    except StopIteration:
        # If no empty columns are found, use the column index after the last non-empty column
        next_empty_column = len(df.columns)  # Get the number of columns (integer)

    # Insert the new empty column with the sheet name
    df.insert(loc=next_empty_column, column=sheet_name, value=pd.NA)  # Use loc for integer index

    # Write the modified DataFrame back to the Excel file
    df.to_excel(writer, sheet_name=sheet_name, index=False)

    # Close the writer to save changes
    writer.close()

# Example usage:
filename = 'aset/asetEdomGanjil2223.xlsx'
for sheet_name in pd.ExcelFile(filename).sheet_names:  # Iterate through all sheets
    # insert_empty_column_with_sheet_name(filename, sheet_name)
    sheet_name

FileNotFoundError: [Errno 2] No such file or directory: 'aset/asetEdomGanjil2223.xlsx'

NameError: name 'df' is not defined